var searchData=
[
  ['managedhudobjective',['ManagedHudObjective',['../d5/d35/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1scoreboards_1_1ManagedHudObjective.html',1,'com::jcwhatever::nucleus::internal::managed::scoreboards']]],
  ['managedobjective',['ManagedObjective',['../d5/da3/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1scoreboards_1_1ManagedObjective.html',1,'com::jcwhatever::nucleus::internal::managed::scoreboards']]],
  ['mapwrapper',['MapWrapper',['../d8/d43/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['mapwrapper_3c_20k_2c_20collection_3c_20v_20_3e_20_3e',['MapWrapper&lt; K, Collection&lt; V &gt; &gt;',['../d8/d43/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['mapwrapper_3c_20string_2c_20loremetaitem_20_3e',['MapWrapper&lt; String, LoreMetaItem &gt;',['../d8/d43/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['mapwrapper_3c_20uuid_2c_20v_20_3e',['MapWrapper&lt; UUID, V &gt;',['../d8/d43/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['marqueedirection',['MarqueeDirection',['../d3/d3d/enumcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1text_1_1dynamic_1_1MarqueeText_1_1MarqueeDirection.html',1,'com::jcwhatever::nucleus::utils::text::dynamic::MarqueeText']]],
  ['marqueetext',['MarqueeText',['../d5/d50/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1text_1_1dynamic_1_1MarqueeText.html',1,'com::jcwhatever::nucleus::utils::text::dynamic']]],
  ['matchableitem',['MatchableItem',['../df/d52/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1items_1_1MatchableItem.html',1,'com::jcwhatever::nucleus::utils::items']]],
  ['matcher',['Matcher',['../d8/d52/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1ConversionCollectionWrapper_1_1Matcher.html',1,'com::jcwhatever::nucleus::collections::wrap::ConversionCollectionWrapper']]],
  ['materialconverter',['MaterialConverter',['../d8/dca/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1converters_1_1MaterialConverter.html',1,'com::jcwhatever::nucleus::utils::converters']]],
  ['materialdataconverter',['MaterialDataConverter',['../d9/dbb/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1converters_1_1MaterialDataConverter.html',1,'com::jcwhatever::nucleus::utils::converters']]],
  ['materialidconverter',['MaterialIDConverter',['../d1/d52/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1converters_1_1MaterialIDConverter.html',1,'com::jcwhatever::nucleus::utils::converters']]],
  ['materialproperty',['MaterialProperty',['../d0/de9/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1materials_1_1MaterialProperty.html',1,'com::jcwhatever::nucleus::utils::materials']]],
  ['materials',['Materials',['../da/d35/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1materials_1_1Materials.html',1,'com::jcwhatever::nucleus::utils::materials']]],
  ['memorydatanode',['MemoryDataNode',['../d8/d60/classcom_1_1jcwhatever_1_1nucleus_1_1storage_1_1MemoryDataNode.html',1,'com::jcwhatever::nucleus::storage']]],
  ['menuinventory',['MenuInventory',['../d3/d41/classcom_1_1jcwhatever_1_1nucleus_1_1views_1_1menu_1_1MenuInventory.html',1,'com::jcwhatever::nucleus::views::menu']]],
  ['menuitem',['MenuItem',['../de/d81/classcom_1_1jcwhatever_1_1nucleus_1_1views_1_1menu_1_1MenuItem.html',1,'com::jcwhatever::nucleus::views::menu']]],
  ['menuitembuilder',['MenuItemBuilder',['../dc/da8/classcom_1_1jcwhatever_1_1nucleus_1_1views_1_1menu_1_1MenuItemBuilder.html',1,'com::jcwhatever::nucleus::views::menu']]],
  ['menuview',['MenuView',['../d9/daf/classcom_1_1jcwhatever_1_1nucleus_1_1views_1_1menu_1_1MenuView.html',1,'com::jcwhatever::nucleus::views::menu']]],
  ['metakey',['MetaKey',['../d9/d22/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaKey.html',1,'com::jcwhatever::nucleus::utils']]],
  ['metakey_3c_20boolean_20_3e',['MetaKey&lt; Boolean &gt;',['../d9/d22/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaKey.html',1,'com::jcwhatever::nucleus::utils']]],
  ['metakey_3c_20com_3a_3ajcwhatever_3a_3anucleus_3a_3aregions_3a_3airegion_20_3e',['MetaKey&lt; com::jcwhatever::nucleus::regions::IRegion &gt;',['../d9/d22/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaKey.html',1,'com::jcwhatever::nucleus::utils']]],
  ['metakey_3c_20integer_20_3e',['MetaKey&lt; Integer &gt;',['../d9/d22/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaKey.html',1,'com::jcwhatever::nucleus::utils']]],
  ['metakey_3c_20long_20_3e',['MetaKey&lt; Long &gt;',['../d9/d22/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaKey.html',1,'com::jcwhatever::nucleus::utils']]],
  ['metastore',['MetaStore',['../d7/d87/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1MetaStore.html',1,'com::jcwhatever::nucleus::utils']]],
  ['missingargumentexception',['MissingArgumentException',['../d0/dde/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1commands_1_1exceptions_1_1MissingArgumentException.html',1,'com::jcwhatever::nucleus::managed::commands::exceptions']]],
  ['missingrequiredresourcepackevent',['MissingRequiredResourcePackEvent',['../d3/db0/classcom_1_1jcwhatever_1_1nucleus_1_1events_1_1respacks_1_1MissingRequiredResourcePackEvent.html',1,'com::jcwhatever::nucleus::events::respacks']]],
  ['mobs',['Mobs',['../d8/dd7/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1entity_1_1mob_1_1Mobs.html',1,'com::jcwhatever::nucleus::managed::entity::mob']]],
  ['mobspecificity',['MobSpecificity',['../d1/d94/enumcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1entity_1_1mobs_1_1property_1_1MobSpecificity.html',1,'com::jcwhatever::nucleus::internal::managed::entity::mobs::property']]],
  ['mobtype',['MobType',['../d2/d3a/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1entity_1_1mobs_1_1property_1_1MobType.html',1,'com::jcwhatever::nucleus::internal::managed::entity::mobs::property']]],
  ['multibimap',['MultiBiMap',['../d9/dae/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1MultiBiMap.html',1,'com::jcwhatever::nucleus::collections']]],
  ['multibimap_3c_20string_2c_20materialdata_20_3e',['MultiBiMap&lt; String, MaterialData &gt;',['../d9/dae/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1MultiBiMap.html',1,'com::jcwhatever::nucleus::collections']]],
  ['multimapwrapper',['MultimapWrapper',['../da/d62/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MultimapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['multimapwrapper_3c_20uuid_2c_20v_20_3e',['MultimapWrapper&lt; UUID, V &gt;',['../da/d62/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1wrap_1_1MultimapWrapper.html',1,'com::jcwhatever::nucleus::collections::wrap']]],
  ['multisnapshotregion',['MultiSnapshotRegion',['../d1/db6/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1MultiSnapshotRegion.html',1,'com::jcwhatever::nucleus::regions']]],
  ['mutablechunkcoords',['MutableChunkCoords',['../dd/d70/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1MutableChunkCoords.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['mutablecoords2d',['MutableCoords2D',['../dc/dc1/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1MutableCoords2D.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['mutablecoords2di',['MutableCoords2Di',['../d7/ddf/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1MutableCoords2Di.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['mutablecoords3d',['MutableCoords3D',['../db/dc7/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1MutableCoords3D.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['mutablecoords3di',['MutableCoords3Di',['../dc/d5e/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1MutableCoords3Di.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['mutablematchableitem',['MutableMatchableItem',['../d7/d5e/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1items_1_1MutableMatchableItem.html',1,'com::jcwhatever::nucleus::utils::items']]]
];
