var searchData=
[
  ['rabbitanimal',['RabbitAnimal',['../df/d3e/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1entity_1_1mobs_1_1property_1_1RabbitAnimal.html',1,'com::jcwhatever::nucleus::internal::managed::entity::mobs::property']]],
  ['rand',['Rand',['../d2/d5d/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1Rand.html',1,'com::jcwhatever::nucleus::utils']]],
  ['readonlyregion',['ReadOnlyRegion',['../da/d43/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1ReadOnlyRegion.html',1,'com::jcwhatever::nucleus::regions']]],
  ['reflectedinstancefields',['ReflectedInstanceFields',['../de/d6d/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1reflection_1_1ReflectedInstanceFields.html',1,'com::jcwhatever::nucleus::internal::managed::reflection']]],
  ['reflection',['Reflection',['../de/d22/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1reflection_1_1Reflection.html',1,'com::jcwhatever::nucleus::managed::reflection']]],
  ['region',['Region',['../d8/d93/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1Region.html',1,'com::jcwhatever::nucleus::regions']]],
  ['regionblockiterator',['RegionBlockIterator',['../d5/d16/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1RegionBlockIterator.html',1,'com::jcwhatever::nucleus::regions']]],
  ['regionchunkfileloader',['RegionChunkFileLoader',['../db/d63/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1file_1_1basic_1_1RegionChunkFileLoader.html',1,'com::jcwhatever::nucleus::regions::file::basic']]],
  ['regionchunkfilewriter',['RegionChunkFileWriter',['../dc/d18/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1file_1_1basic_1_1RegionChunkFileWriter.html',1,'com::jcwhatever::nucleus::regions::file::basic']]],
  ['regionchunksection',['RegionChunkSection',['../d2/d5d/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1data_1_1RegionChunkSection.html',1,'com::jcwhatever::nucleus::regions::data']]],
  ['regioneventpriority',['RegionEventPriority',['../d5/de4/enumcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1options_1_1RegionEventPriority.html',1,'com::jcwhatever::nucleus::regions::options']]],
  ['regioneventreason',['RegionEventReason',['../d7/d56/enumcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1regions_1_1RegionEventReason.html',1,'com::jcwhatever::nucleus::internal::regions']]],
  ['regionfileloader',['RegionFileLoader',['../d6/d2c/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1file_1_1basic_1_1RegionFileLoader.html',1,'com::jcwhatever::nucleus::regions::file::basic']]],
  ['regionfilewriter',['RegionFileWriter',['../dd/d56/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1file_1_1basic_1_1RegionFileWriter.html',1,'com::jcwhatever::nucleus::regions::file::basic']]],
  ['regionmanager',['RegionManager',['../d9/da4/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1RegionManager.html',1,'com::jcwhatever::nucleus::regions']]],
  ['regionmanager_3c_20internalscriptregion_20_3e',['RegionManager&lt; InternalScriptRegion &gt;',['../d9/da4/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1RegionManager.html',1,'com::jcwhatever::nucleus::regions']]],
  ['regionownerchangedevent',['RegionOwnerChangedEvent',['../dd/d92/classcom_1_1jcwhatever_1_1nucleus_1_1events_1_1regions_1_1RegionOwnerChangedEvent.html',1,'com::jcwhatever::nucleus::events::regions']]],
  ['regionpriorityinfo',['RegionPriorityInfo',['../d2/d7c/interfacecom_1_1jcwhatever_1_1nucleus_1_1regions_1_1RegionPriorityInfo.html',1,'com::jcwhatever::nucleus::regions']]],
  ['regionscommand',['RegionsCommand',['../d4/d47/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1commands_1_1scripts_1_1regions_1_1RegionsCommand.html',1,'com::jcwhatever::nucleus::internal::commands::scripts::regions']]],
  ['regionscommand',['RegionsCommand',['../de/d2f/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1commands_1_1regions_1_1RegionsCommand.html',1,'com::jcwhatever::nucleus::internal::commands::regions']]],
  ['regionselection',['RegionSelection',['../d3/dad/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1regionselect_1_1RegionSelection.html',1,'com::jcwhatever::nucleus::providers::regionselect']]],
  ['regionshape',['RegionShape',['../df/d5b/enumcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1data_1_1RegionShape.html',1,'com::jcwhatever::nucleus::regions::data']]],
  ['removalpolicy',['RemovalPolicy',['../d6/d0d/enumcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1ElementCounter_1_1RemovalPolicy.html',1,'com::jcwhatever::nucleus::collections::ElementCounter']]],
  ['requestcontextbuilder2',['RequestContextBuilder2',['../dd/d5d/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1commands_1_1response_1_1RequestContef5887e3c23a330d300bdf8ea815bea92.html',1,'com::jcwhatever::nucleus::internal::managed::commands::response::RequestContextBuilder']]],
  ['requestcontextbuilder3',['RequestContextBuilder3',['../de/da0/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1commands_1_1response_1_1RequestConteaf877556084c73753cd50fd54cf09a6f.html',1,'com::jcwhatever::nucleus::internal::managed::commands::response::RequestContextBuilder']]],
  ['requestcontextbuilder4',['RequestContextBuilder4',['../df/d15/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1commands_1_1response_1_1RequestContee80941f9f84adcb513173cb9fac78c44.html',1,'com::jcwhatever::nucleus::internal::managed::commands::response::RequestContextBuilder']]],
  ['resourcepacks',['ResourcePacks',['../dc/d6c/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1resourcepacks_1_1ResourcePacks.html',1,'com::jcwhatever::nucleus::managed::resourcepacks']]],
  ['resourcepacksounds',['ResourcePackSounds',['../d9/d3b/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1resourcepacks_1_1ResourcePackSounds.html',1,'com::jcwhatever::nucleus::internal::managed::resourcepacks']]],
  ['resourcepackstatus',['ResourcePackStatus',['../d0/d05/enumcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1resourcepacks_1_1ResourcePackStatus.html',1,'com::jcwhatever::nucleus::managed::resourcepacks']]],
  ['resourcesoundendevent',['ResourceSoundEndEvent',['../da/d59/classcom_1_1jcwhatever_1_1nucleus_1_1events_1_1sounds_1_1ResourceSoundEndEvent.html',1,'com::jcwhatever::nucleus::events::sounds']]],
  ['respackscommand',['ResPacksCommand',['../d4/d6c/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1commands_1_1respacks_1_1ResPacksCommand.html',1,'com::jcwhatever::nucleus::internal::commands::respacks']]],
  ['responserequestor',['ResponseRequestor',['../d5/d62/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1commands_1_1response_1_1ResponseRequestor.html',1,'com::jcwhatever::nucleus::managed::commands::response']]],
  ['responsetype',['ResponseType',['../de/d3c/classcom_1_1jcwhatever_1_1nucleus_1_1managed_1_1commands_1_1response_1_1ResponseType.html',1,'com::jcwhatever::nucleus::managed::commands::response']]],
  ['restorableregion',['RestorableRegion',['../d4/d94/classcom_1_1jcwhatever_1_1nucleus_1_1regions_1_1RestorableRegion.html',1,'com::jcwhatever::nucleus::regions']]],
  ['restorelocation',['RestoreLocation',['../df/dd4/enumcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1player_1_1PlayerState_1_1RestoreLocation.html',1,'com::jcwhatever::nucleus::utils::player::PlayerState']]],
  ['result',['Result',['../d2/dd6/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1Result.html',1,'com::jcwhatever::nucleus::utils']]],
  ['result',['Result',['../d3/dfc/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1observer_1_1future_1_1Result.html',1,'com::jcwhatever::nucleus::utils::observer::future']]],
  ['result_3c_20com_3a_3ajcwhatever_3a_3anucleus_3a_3aproviders_3a_3afriends_3a_3aifriend_20_3e',['Result&lt; com::jcwhatever::nucleus::providers::friends::IFriend &gt;',['../d2/dd6/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1Result.html',1,'com::jcwhatever::nucleus::utils']]],
  ['result_3c_20uuid_20_3e',['Result&lt; UUID &gt;',['../d2/dd6/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1Result.html',1,'com::jcwhatever::nucleus::utils']]],
  ['resultbuilder',['ResultBuilder',['../de/d56/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1observer_1_1future_1_1ResultBuilder.html',1,'com::jcwhatever::nucleus::utils::observer::future']]],
  ['retrievableset',['RetrievableSet',['../d1/dc8/classcom_1_1jcwhatever_1_1nucleus_1_1collections_1_1RetrievableSet.html',1,'com::jcwhatever::nucleus::collections']]]
];
