var searchData=
[
  ['nameddatamanager',['NamedDataManager',['../d4/d0b/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['nameddatamanager_3c_20t_20_3e',['NamedDataManager&lt; T &gt;',['../d4/d0b/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager',['NamedInsensitiveDataManager',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20ifloatingitem_20_3e',['NamedInsensitiveDataManager&lt; IFloatingItem &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20ikit_20_3e',['NamedInsensitiveDataManager&lt; IKit &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20iresourcepack_20_3e',['NamedInsensitiveDataManager&lt; IResourcePack &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20iscriptitem_20_3e',['NamedInsensitiveDataManager&lt; IScriptItem &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20namedlocation_20_3e',['NamedInsensitiveDataManager&lt; NamedLocation &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivedatamanager_3c_20t_20_3e',['NamedInsensitiveDataManager&lt; T &gt;',['../d9/d27/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveDataManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedinsensitivemanager',['NamedInsensitiveManager',['../d3/d05/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedInsensitiveManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedlocation',['NamedLocation',['../da/d2a/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1coords_1_1NamedLocation.html',1,'com::jcwhatever::nucleus::utils::coords']]],
  ['namedmanager',['NamedManager',['../dd/d51/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedmanager_3c_20mobtype_20_3e',['NamedManager&lt; MobType &gt;',['../dd/d51/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedmanager_3c_20t_20_3e',['NamedManager&lt; T &gt;',['../dd/d51/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1managers_1_1NamedManager.html',1,'com::jcwhatever::nucleus::utils::managers']]],
  ['namedmaterialdata',['NamedMaterialData',['../d1/d05/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1materials_1_1NamedMaterialData.html',1,'com::jcwhatever::nucleus::utils::materials']]],
  ['namedupdateagents',['NamedUpdateAgents',['../d8/dae/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1observer_1_1update_1_1NamedUpdateAgents.html',1,'com::jcwhatever::nucleus::utils::observer::update']]],
  ['neconomycommand',['NEconomyCommand',['../d2/daf/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1commands_1_1economy_1_1NEconomyCommand.html',1,'com::jcwhatever::nucleus::internal::commands::economy']]],
  ['newlinecomponent',['NewLineComponent',['../df/d3d/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1text_1_1components_1_1NewLineComponent.html',1,'com::jcwhatever::nucleus::utils::text::components']]],
  ['nfriendscommand',['NFriendsCommand',['../d2/d2d/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1commands_1_1friends_1_1NFriendsCommand.html',1,'com::jcwhatever::nucleus::internal::commands::friends']]],
  ['nmsanvilviewhandler',['NmsAnvilViewHandler',['../d0/ddd/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1nms_1_1NmsAnvilViewHandler.html',1,'com::jcwhatever::nucleus::internal::managed::nms']]],
  ['nmschathandler',['NmsChatHandler',['../d8/d5d/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1managed_1_1nms_1_1NmsChatHandler.html',1,'com::jcwhatever::nucleus::internal::managed::nms']]],
  ['nmsmanager',['NmsManager',['../de/d64/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1nms_1_1NmsManager.html',1,'com::jcwhatever::nucleus::utils::nms']]],
  ['nmsutils',['NmsUtils',['../d0/d84/classcom_1_1jcwhatever_1_1nucleus_1_1utils_1_1nms_1_1NmsUtils.html',1,'com::jcwhatever::nucleus::utils::nms']]],
  ['npcclickevent',['NpcClickEvent',['../d7/dd1/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcClickEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npccreateevent',['NpcCreateEvent',['../dd/d9d/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcCreateEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdamagebyblockevent',['NpcDamageByBlockEvent',['../d6/d0a/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDamageByBlockEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdamagebyentityevent',['NpcDamageByEntityEvent',['../db/d5c/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDamageByEntityEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdamageevent',['NpcDamageEvent',['../df/da0/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDamageEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdeathevent',['NpcDeathEvent',['../d5/da3/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDeathEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdespawnevent',['NpcDespawnEvent',['../d4/da5/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDespawnEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcdespawnreason',['NpcDespawnReason',['../de/d74/enumcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDespawnEvent_1_1NpcDespawnReason.html',1,'com::jcwhatever::nucleus::providers::npc::events::NpcDespawnEvent']]],
  ['npcdisposeevent',['NpcDisposeEvent',['../d8/dc6/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcDisposeEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcentitytypechangeevent',['NpcEntityTypeChangeEvent',['../d5/de8/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcEntityTypeChangeEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcevent',['NpcEvent',['../d1/d7c/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcleftclickevent',['NpcLeftClickEvent',['../dc/d68/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcLeftClickEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcplayerevent',['NpcPlayerEvent',['../d1/d85/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcPlayerEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcpushevent',['NpcPushEvent',['../df/df9/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcPushEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcrightclickevent',['NpcRightClickEvent',['../dd/d2f/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcRightClickEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcrunnabletrait',['NpcRunnableTrait',['../d3/d2a/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1traits_1_1NpcRunnableTrait.html',1,'com::jcwhatever::nucleus::providers::npc::traits']]],
  ['npcs',['Npcs',['../dd/d86/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1Npcs.html',1,'com::jcwhatever::nucleus::providers::npc']]],
  ['npcscriptaction',['NpcScriptAction',['../de/db8/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1ai_1_1actions_1_1NpcScriptAction.html',1,'com::jcwhatever::nucleus::providers::npc::ai::actions']]],
  ['npcscriptbehaviour',['NpcScriptBehaviour',['../df/d1a/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1ai_1_1NpcScriptBehaviour.html',1,'com::jcwhatever::nucleus::providers::npc::ai']]],
  ['npcscriptbehaviour_3c_20inpcactionagent_20_3e',['NpcScriptBehaviour&lt; INpcActionAgent &gt;',['../df/d1a/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1ai_1_1NpcScriptBehaviour.html',1,'com::jcwhatever::nucleus::providers::npc::ai']]],
  ['npcscriptbehaviour_3c_20inpcgoalagent_20_3e',['NpcScriptBehaviour&lt; INpcGoalAgent &gt;',['../df/d1a/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1ai_1_1NpcScriptBehaviour.html',1,'com::jcwhatever::nucleus::providers::npc::ai']]],
  ['npcscriptgoal',['NpcScriptGoal',['../d3/dc0/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1ai_1_1goals_1_1NpcScriptGoal.html',1,'com::jcwhatever::nucleus::providers::npc::ai::goals']]],
  ['npcspawnevent',['NpcSpawnEvent',['../d7/dfb/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcSpawnEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npcspawnreason',['NpcSpawnReason',['../d5/d8c/enumcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcSpawnEvent_1_1NpcSpawnReason.html',1,'com::jcwhatever::nucleus::providers::npc::events::NpcSpawnEvent']]],
  ['npctargetedevent',['NpcTargetedEvent',['../d4/d21/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1events_1_1NpcTargetedEvent.html',1,'com::jcwhatever::nucleus::providers::npc::events']]],
  ['npctrait',['NpcTrait',['../d3/de8/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1traits_1_1NpcTrait.html',1,'com::jcwhatever::nucleus::providers::npc::traits']]],
  ['npctraittype',['NpcTraitType',['../d2/d1c/classcom_1_1jcwhatever_1_1nucleus_1_1providers_1_1npc_1_1traits_1_1NpcTraitType.html',1,'com::jcwhatever::nucleus::providers::npc::traits']]],
  ['nuclang',['NucLang',['../de/d31/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1NucLang.html',1,'com::jcwhatever::nucleus::internal']]],
  ['nucleus',['Nucleus',['../d9/de9/classcom_1_1jcwhatever_1_1nucleus_1_1Nucleus.html',1,'com::jcwhatever::nucleus']]],
  ['nucleuscurrency',['NucleusCurrency',['../d7/d23/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1economy_1_1NucleusCurrency.html',1,'com::jcwhatever::nucleus::internal::providers::economy']]],
  ['nucleuseconomyprovider',['NucleusEconomyProvider',['../da/d32/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1economy_1_1NucleusEconomyProvider.html',1,'com::jcwhatever::nucleus::internal::providers::economy']]],
  ['nucleusfastmathprovider',['NucleusFastMathProvider',['../d8/dd3/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1math_1_1NucleusFastMathProvider.html',1,'com::jcwhatever::nucleus::internal::providers::math']]],
  ['nucleusfriendsprovider',['NucleusFriendsProvider',['../de/d87/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1friends_1_1NucleusFriendsProvider.html',1,'com::jcwhatever::nucleus::internal::providers::friends']]],
  ['nucleusjailprovider',['NucleusJailProvider',['../d9/d25/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1jail_1_1NucleusJailProvider.html',1,'com::jcwhatever::nucleus::internal::providers::jail']]],
  ['nucleuskitcontext',['NucleusKitContext',['../db/d18/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1kits_1_1NucleusKitContext.html',1,'com::jcwhatever::nucleus::internal::providers::kits']]],
  ['nucleuskitmodifier',['NucleusKitModifier',['../d9/d54/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1kits_1_1NucleusKitModifier.html',1,'com::jcwhatever::nucleus::internal::providers::kits']]],
  ['nucleuskitprovider',['NucleusKitProvider',['../d8/dae/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1kits_1_1NucleusKitProvider.html',1,'com::jcwhatever::nucleus::internal::providers::kits']]],
  ['nucleusloadedevent',['NucleusLoadedEvent',['../d1/d8f/classcom_1_1jcwhatever_1_1nucleus_1_1events_1_1NucleusLoadedEvent.html',1,'com::jcwhatever::nucleus::events']]],
  ['nucleusplugin',['NucleusPlugin',['../df/d5e/classcom_1_1jcwhatever_1_1nucleus_1_1NucleusPlugin.html',1,'com::jcwhatever::nucleus']]],
  ['nucleusrotationmatrix',['NucleusRotationMatrix',['../d5/db1/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1math_1_1NucleusRotationMatrix.html',1,'com::jcwhatever::nucleus::internal::providers::math']]],
  ['nucleusselectionprovider',['NucleusSelectionProvider',['../dc/de1/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1providers_1_1selection_1_1NucleusSelectionProvider.html',1,'com::jcwhatever::nucleus::internal::providers::selection']]],
  ['nucmsg',['NucMsg',['../d4/d75/classcom_1_1jcwhatever_1_1nucleus_1_1internal_1_1NucMsg.html',1,'com::jcwhatever::nucleus::internal']]]
];
